a:1:{s:5:"query";a:1:{s:5:"pages";a:2:{i:-1;a:3:{s:2:"ns";i:0;s:5:"title";s:15:"Events by month";s:7:"missing";s:0:"";}i:36225;a:4:{s:6:"pageid";i:36225;s:2:"ns";i:0;s:5:"title";s:4:"2011";s:9:"revisions";a:1:{i:0;a:6:{s:4:"user";s:5:"Yerpo";s:9:"timestamp";s:20:"2014-03-27T13:32:43Z";s:7:"comment";s:135:"Undid revision 601490958 by [[Special:Contributions/Ouddorp|Ouddorp]] ([[User talk:Ouddorp|talk]]) - yes, local. See [[WP:OTHERSTUFF]].";s:13:"contentformat";s:11:"text/x-wiki";s:12:"contentmodel";s:8:"wikitext";s:1:"*";s:57625:"{{pp-move-indef}}
{{Year dab|2011}}
{{Events by month|2011}}
{{Year nav|2011}}
{{C21 year in topic}}{{Use mdy dates|date=March 2011}}
{{Year article header|2011}}<!-- This template works perfectly, and replaces the following:
'''2011''' ('''[[Roman numerals|MMXI]]''') was a [[common year]] that [[common year starting on Saturday|started on a Saturday]] in the [[Gregorian calendar]]. It was the 2011th year of the [[Common Era]] (CE) and ''[[Anno Domini]]'' (AD) designations; the 11th year of the [[3rd millennium]] and of the [[21st century]]; and the 2nd of the [[2010s]].-->

The [[United Nations]] designated '''2011''' as the [[International Year of Forests]] and the [[International Year of Chemistry]].<ref>{{cite web|title=United Nations Observances|url=http://www.un.org/en/events/observances/|publisher=United Nations|accessdate=5 July 2012}}</ref> It was marked by a wave of revolutions in the Arab World known as the [[Arab Spring]], including the beginnings of several unresolved protest movements and armed conflicts.

==Events==

===January===
<!-- Please do not add the shooting of Gabrielle Giffords in Tucson, Arizona. It is a local US centric event. If you believe it should be added, please get consensus on the talk page first. -->
* [[January 1]] &ndash; [[Estonia]] officially adopts the [[Euro]] currency and becomes the 17th [[Eurozone]] country.<ref>{{cite web|url=http://www.bbc.co.uk/news/world-europe-12098513 |title=BBC News - Estonia becomes 17th member of the euro zone 31/12/2010 BBC News |publisher=Bbc.co.uk |date=2010-12-31 |accessdate=2012-05-06}}</ref>
* [[January 4]] &ndash; [[Tunisia]]n street vendor [[Mohamed Bouazizi]] dies after [[Self-immolation|setting himself on fire]] a month earlier, sparking anti-government protests in Tunisia and later other [[Arab world|Arab nations]]. These protests become known collectively as the [[Arab Spring]].<ref>{{cite news|url=http://www.bbc.co.uk/news/world-africa-16230190 |author=Gardner, Frank |title=Tunisia one year on: Where the Arab Spring started |date=2011-12-17 |publisher=BBC News |accessdate=2012-01-15}}</ref><ref>{{cite news |agency=Associated Press |date=2011-12-17 |url=http://www.cbc.ca/news/world/story/2011/12/17/tunisia-anniversary-arabspring.html |title=Vegetable seller who inspired Arab Spring honoured |publisher=CBC News |accessdate=2012-01-15}}</ref>
* [[January 9]] &ndash; [[January 15|15]] &ndash; [[Southern Sudan]] holds a [[Southern Sudanese independence referendum, 2011|referendum on independence]]. The Sudanese electorate votes in favour of independence, paving the way for the creation of the new state in July.<ref>{{cite web|url=http://www.almanar.com.lb/newssite/NewsDetails.aspx?id=170242&language=en |title=Al-ManarTV:: South Sudan Referendum Wraps up, Khartoum Vows to Recognize Results 15/01/2011 |publisher=Almanar.com.lb |date=2011-01-15 |accessdate=2011-01-31}}{{dead link|date=June 2011}}</ref><ref>[http://www.telegraph.co.uk/news/worldnews/africaandindianocean/sudan/8246615/Sudan-referendum-whats-being-voted-on-and-what-will-happen.html ''Sudan referendum: what's being voted on and what will happen?''] The Telegraph. 8 January 2011</ref>
* [[January 11]] &ndash; [[January 2011 Rio de Janeiro floods and mudslides|Flooding and mudslides]] in the Brazilian state of [[Rio de Janeiro (state)|Rio de Janeiro]] kills 903.<ref>{{cite news|url=http://www1.folha.uol.com.br/cotidiano/863364-equipe-aeropolicial-improvisa-e-arrisca-para-resgatar-vitimas-das-chuvas-no-rj.shtml | title=Equipe aeropolicial improvisa e arrisca para resgatar vítimas das chuvas no RJ | accessdate=20 January 2011 | date=20 January 2011 | publisher=[[Folha]] |work=[[Universo Online|UOL]] | language = Portuguese}}</ref>
* [[January 14]] &ndash; [[Arab Spring]]: The [[Tunisia]]n government falls after a month of increasingly violent protests; [[President of Tunisia|President]] [[Zine El Abidine Ben Ali]] flees to [[Saudi Arabia]] after 23 years in power.<ref name="autogenerated1">{{cite news|author=Wyre Davies |url=http://www.bbc.co.uk/news/world-africa-12195025 |title=BBC News – Tunisia: President Zine al-Abidine Ali forced out |publisher=BBC News |date=15 December 2010 |accessdate=2011-01-14| archiveurl= http://web.archive.org/web/20110115053136/http://www.bbc.co.uk/news/world-africa-12195025| archivedate= 15 January 2011 <!--DASHBot-->| deadurl= no}}</ref><ref>{{cite web|url=http://www.indybay.org/newsitems/2011/01/16/18669320.php |title=Uprising in Tunisia: People Power topples Ben Ali regime |publisher=Indybay |date=16 January 2011 |accessdate=2011-01-26}}</ref>
* [[January 24]] &ndash; 37 people are killed and more than 180 others wounded in [[2011 Domodedovo International Airport bombing|a bombing]] at [[Domodedovo International Airport]] in Moscow, Russia.<ref name="Ferris-Rotman">{{cite news |url=http://www.reuters.com/article/idUSTRE70N2TQ20110124 |title=Suicide bomber kills 31 at Russia's biggest airport |author=Amie Ferris-Rotman |date=24 January 2011 |work=[[Reuters]] |accessdate=2011-06-21}}</ref><ref name="37deaths">{{ru icon}}{{cite news|url=http://rian.ru/society/20110224/338222803.html|title=Число жертв теракта в Домодедово возросло до 37|publisher=[[RIA Novosti]]|date=24 February 2011|accessdate=24 February 2011}}</ref><ref name="BBC">{{cite news|url=http://www.bbc.co.uk/news/world-europe-12268662|title=Moscow bombing: Carnage at Russia's Domodedovo airport|publisher=BBC News|author=Steve Rosenberg|date=24 January 2011|accessdate=24 January 2011| archiveurl= http://web.archive.org/web/20110125024514/http://www.bbc.co.uk/news/world-europe-12268662| archivedate= 25 January 2011 <!--DASHBot-->| deadurl= no}}</ref>

===February===
<!-- Please do not add the Christchurch earthquake. The consensus is that the event wasn't significant enough on global scale. If you still believe it should be added, get consensus on the talk page first. -->
* [[February 11]] &ndash; Arab Spring: [[President of Egypt|Egyptian President]] [[Hosni Mubarak]] resigns after [[Egyptian Revolution of 2011|widespread protests]] calling for his departure, leaving control of Egypt in the hands of the [[Egyptian military|military]] until a general election can be held.<ref>{{cite news|url=http://english.aljazeera.net/news/middleeast/2011/02/201121125158705862.html | title=Hosni Mubarak resigns as president | accessdate=11 February 2011 | date=11 February 2011 | publisher=[[AlJazeera]] | archiveurl= http://web.archive.org/web/20110211082027/http://english.aljazeera.net/news/middleeast/2011/02/201121125158705862.html| archivedate= 11 February 2011 <!--DASHBot-->| deadurl= no}}</ref>
* [[February 22]] &ndash; [[March 14]] &ndash; Uncertainty over Libyan oil output causes [[crude oil]] prices to rise 20% over a two-week period following the Arab Spring,<ref>{{cite news|url=http://online.wsj.com/article/SB10001424052748703610604576158613735835374.html|title=The Stealth Return of $100 Oil|date=February 22, 2011|accessdate=March 12, 2011|newspaper=[[The Wall Street Journal]]|first1=Jerry A.|last1=Dicolo|first2=Brian|last2=Baskin| archiveurl= http://web.archive.org/web/20110224063242/http://online.wsj.com/article/SB10001424052748703610604576158613735835374.html| archivedate= 24 February 2011 <!--DASHBot-->| deadurl= no}}</ref> causing the 2011 energy crisis.

===March===
* [[March 11]] &ndash; A 9.0-magnitude [[2011 Tōhoku earthquake and tsunami|earthquake and subsequent tsunami]] hit the east of Japan, killing 15,840 and leaving another 3,926 missing. Tsunami warnings are issued in 50 countries and territories. [[Fukushima Daiichi nuclear disaster|Emergencies]] are declared at four nuclear power plants affected by the quake.<ref>{{cite news|title=Japan earthquake live blog: Death toll rises amid widespread destruction| url = http://news.blogs.cnn.com/2011/03/12/japan-earthquake-live-blog-death-toll-rises-amid-widespread-destruction/| date=12 March 2011| work =CNN blog |publisher=TimeWarner|accessdate=12 March 2011| archiveurl= http://web.archive.org/web/20110316132608/http://news.blogs.cnn.com/2011/03/12/japan-earthquake-live-blog-death-toll-rises-amid-widespread-destruction/| archivedate= 16 March 2011 <!--DASHBot-->| deadurl= no}}</ref>
* [[March 15]]
** Arab Spring: [[Hamad bin Isa Al Khalifa]], [[King of Bahrain]] declares a three-month [[state of emergency]] as troops from the [[Gulf Co-operation Council]] are sent to quell the [[2011 Bahraini uprising|civil unrest]].<ref name="BBCBahr15Mar">{{cite news | title = Bahrain King Declares State of Emergency after Protests | author= Staff writer | url = http://www.bbc.co.uk/news/world-middle-east-12745608 | publisher = BBC News | date=15 March 2011 | accessdate=15 April 2011 | authorlink = Staff writer| archiveurl= http://web.archive.org/web/20110405202821/http://www.bbc.co.uk/news/world-middle-east-12745608| archivedate= 5 April 2011 <!--DASHBot-->| deadurl= no}}</ref><ref>{{cite news | author = Staff writer | title = Two Killed in Bahrain Violence Despite Martial Law | publisher = BBC News | url = http://www.bbc.co.uk/news/world-middle-east-12751464 | date=15 March 2011 | accessdate=15 April 2011 | authorlink = Staff writer| archiveurl= http://web.archive.org/web/20110405202839/http://www.bbc.co.uk/news/world-middle-east-12751464| archivedate= 5 April 2011 <!--DASHBot-->| deadurl= no}}</ref>
** Arab Spring: The [[Syrian Civil War]] begins.
* [[March 17]] &ndash; Arab Spring and the [[Libyan civil war]]:  The [[United Nations Security Council]] votes 10-0 to create a [[Libyan no-fly zone|no-fly zone]] over Libya in response to allegations of government aggression against civilians.<ref>{{cite web|url=http://www.libyafeb17.com/ |title=libyafeb17.com |publisher=libyafeb17.com |date= |accessdate=2012-05-06}}</ref>
* [[March 19]] &ndash; Arab Spring and the Libyan civil war: In light of continuing attacks on Libyan rebels by forces in support of leader [[Muammar Gaddafi]],<ref>{{cite news|url=http://www.msnbc.msn.com/id/42164455/ns/world_news-mideastn_africa/|title=World leaders launch military action in Libya|date=19 March 2011|accessdate=19 March 2011|publisher=[[MSNBC.com]]| archiveurl= http://web.archive.org/web/20110501120756/http://www.msnbc.msn.com/id/42164455/ns/world_news-mideastn_africa/| archivedate= 1 May 2011 <!--DASHBot-->| deadurl= no}}</ref> military intervention authorized under [[United Nations Security Council Resolution 1973|UNSCR 1973]] begins as French fighter jets make reconnaissance flights over Libya.<ref>{{cite news|url=http://www.nytimes.com/2011/03/20/world/africa/20libya.html|title=France Sends Military Flights Over Libya|date=19 March 2011|accessdate=19 March 2011|newspaper=[[The New York Times]]|first1=David D.|last1=Kirkpatrick|first2=Elisabeth|last2=Bumiller| archiveurl= http://web.archive.org/web/20110331024232/http://www.nytimes.com/2011/03/20/world/africa/20libya.html| archivedate= 31 March 2011 <!--DASHBot-->| deadurl= no}}</ref>

===April===
* [[April 11]] &ndash; Former [[List of heads of state of Côte d'Ivoire|Ivorian President]] [[Laurent Gbagbo]] is arrested in his home in [[Abidjan]] by supporters of elected President [[Alassane Ouattara]], with support from French forces; this effectively ends the [[2010–2011 Ivorian crisis]] and [[Second Ivorian Civil War|civil war]].<ref>{{cite news|url=http://af.reuters.com/article/topNews/idAFJOE73A0MX20110411 |title=Gbagbo, wife in Ouattara's custody in I.Coast: UN &#124; Top News &#124; Reuters |publisher=Af.reuters.com |date=11 April 2011|accessdate=11 April 2011| archiveurl= http://web.archive.org/web/20110426045833/http://af.reuters.com/article/topNews/idAFJOE73A0MX20110411| archivedate= 26 April 2011 <!--DASHBot-->| deadurl= no}}</ref>
* [[April 29]] &ndash; An estimated two billion people<ref>{{cite news |last=Grimley |first=Naomi |url=http://www.bbc.co.uk/news/world-13245069 |title=Royal wedding: The world watches William and Kate |publisher=BBC News |date=29 April 2011 |accessdate=16 May 2011}}</ref> watch the [[Wedding of Prince William and Catherine Middleton|wedding]] of [[Prince William, Duke of Cambridge]] and [[Catherine, Duchess of Cambridge|Catherine Middleton]] at [[Westminster Abbey]] in [[London]].

===May===
<!-- Note that, although the death was on May 2 (Pakistani time, UTC+6), the announcement was on May 1 (EDT, UTC-4) -->
* [[May 1]] &ndash; U.S. President Barack Obama announces that [[Osama bin Laden]], the founder and leader of the militant group [[Al-Qaeda]], has been [[Death of Osama bin Laden|killed]] on May 2, 2011 during an American military operation in [[Pakistan]].<ref>{{cite news |last=Goldman |first=Adam |last2=Brummitt |first2=Chris |url=http://news.yahoo.com/s/ap/20110502/ap_on_re_us/us_bin_laden |title=Bin Laden's demise: Long pursuit, burst of gunfire |agency=Associated Press |date=2 May 2011|accessdate=16 May 2011| archiveurl= http://web.archive.org/web/20110513040530/http://news.yahoo.com/s/ap/20110502/ap_on_re_us/us_bin_laden| archivedate= 13 May 2011 <!--DASHBot-->| deadurl= no}}</ref>
* [[May 16]] &ndash; The European Union agrees to a €78&nbsp;billion rescue deal for Portugal. The bailout loan will be equally split between the [[European Financial Stabilisation Mechanism]], the [[European Financial Stability Facility]], and the [[International Monetary Fund]].<ref>{{cite news | url=http://www.bbc.co.uk/news/business-13408497 | title=Portugal's 78bn euro bail-out is formally approved | work=BBC Business News | date=16 May 2011 | agency=BBC | accessdate=13 November 2011 | publisher=bbc.co.uk}}</ref>
* [[May 26]] &ndash; Former [[Bosnia]]n [[Serb]] Army commander [[Ratko Mladić]], wanted for genocide, war crimes and crimes against humanity, is arrested in [[Serbia]].<ref>{{cite web|author=Interpol |url=http://www.interpol.int/public/Data/Wanted/Notices/Data/1995/54/1995_47754.asp |archiveurl=http://web.archive.org/web/20090526144843/http://www.interpol.int/public/Data/Wanted/Notices/Data/1995/54/1995_47754.asp |archivedate=2009-05-26 |title=Interpol: Wanted MLADIC, Ratko |publisher=Interpol.int |accessdate=2011-05-26}}</ref><ref>{{cite news|url=http://www.telegraph.co.uk/news/worldnews/europe/serbia/8537878/Ratko-Mladic-war-crimes-fugitive-arrested-in-Serbia.html|title=Ratko Mladic: war crimes fugitive 'arrested in Serbia'|last=Wardrop|first=Murray|date=26 May 2011|work=[[The Daily Telegraph]]|publisher=[[Telegraph News and Media]]|accessdate=26 May 2011|location=London}}</ref>

===June===
* [[June 4]] &ndash; Chile's [[Puyehue-Cordón Caulle|Puyehue volcano]] [[2011 Puyehue eruption|erupts]], causing air traffic cancellations across South America, New Zealand, Australia and forcing over 3,000 people to evacuate.
* [[June 5]] &ndash; Arab Spring: [[List of Presidents of Yemen|Yemeni President]] [[Ali Abdullah Saleh]] travels to [[Saudi Arabia]] for treatment of an injury sustained during an [[Battle of Sana'a|attack on the presidential palace]]. [[2011 Yemeni uprising|Protesters]] celebrate his transfer of power to his [[List of Presidents of Yemen|Vice-President]] [[Abd al-Rab Mansur al-Hadi]].<ref>{{cite news|url=http://www.washingtonpost.com/world/middle-east/speculation-grows-on-yemeni-presidents-condition/2011/06/04/AGpN9xIH_story.html |title=Yemeni crowds celebrate after president transfers power, flies to Saudi Arabia|last=Londono|first=Ernesto|date=5 June 2011|work=[[The Washington Post]]|publisher=The Washington Post|accessdate=5 June 2011}}</ref>
* [[June 12]] &ndash; Arab Spring: Thousands of [[Syria]]ns flee to Turkey as Syrian troops lay [[Siege of Jisr ash-Shugur|siege to]] [[Jisr ash-Shugur]].<ref>{{cite news|url=http://www.rte.ie/news/2011/0612/syria.html |title=UN in call over Syrian refugee crisis|date=12 June 2011|work=[[RTE]]|publisher=[[RTE]]|accessdate=12 June 2011}}</ref>

===July===
* [[July 7]] &ndash; The world's first [[Artificial organ|artificial]] [[organ transplant]] is achieved, using an artificial [[windpipe]] coated with [[stem cells]].<ref>{{cite news |title=Surgeons carry out first synthetic windpipe transplant |date=7 July 2011|work=[[BBC]]|publisher=BBC|accessdate=8 July 2011 |url=http://www.bbc.co.uk/news/health-14047670| archiveurl= http://web.archive.org/web/20110708015106/http://www.bbc.co.uk/news/health-14047670| archivedate= 8 July 2011 <!--DASHBot-->| deadurl= no}}</ref>
* [[July 9]] &ndash; [[South Sudan]] secedes from [[Sudan]], per the result of the [[Southern Sudanese independence referendum, 2011|independence referendum]] held in January.<ref>{{cite news|url=http://www.bbc.co.uk/news/world-africa-14069082 |title=South Sudan: New nation|date=24 July 2013|work=[[BBC]]|publisher=BBC|accessdate=23 October 2013| archiveurl= | archivedate=  <!--DASHBot-->| deadurl= no}}</ref>
* [[July 14]] &ndash; [[South Sudan]] joins the [[United Nations]] as the 194th member.{{citation needed|date=December 2013}}
* [[July 20]]
** [[Goran Hadžić]] is detained in Serbia, becoming the last of 161 people indicted by the [[International Criminal Tribunal for the former Yugoslavia]].<ref>{{cite web|url=http://www.google.com/hostednews/ap/article/ALeqM5gN0BSyDw5sirbLulQXqgi4DslMtQ?docId=9188fbcd8b194ff79407247b3df94840|title=The Associated Press: Serbia arrests last Balkan war crimes fugitive|publisher=Google.com|accessdate=2011-07-21| archiveurl= http://web.archive.org/web/20110720111844/http://www.google.com/hostednews/ap/article/ALeqM5gN0BSyDw5sirbLulQXqgi4DslMtQ?docId=9188fbcd8b194ff79407247b3df94840| archivedate= 20 July 2011 <!--DASHBot-->| deadurl= no}}</ref>
** The [[United Nations]] declares a [[2011 Horn of Africa famine|famine]] in southern [[Somalia]], the first in over 30 years.<ref>{{cite news|url=http://www.cbc.ca/news/world/story/2011/07/18/un-famine-east-africa.html|title=Somalia on verge of famine|date=18 July 2011|publisher=CBC News|accessdate=18 July 2011| archiveurl= http://web.archive.org/web/20110720035002/http://www.cbc.ca/news/world/story/2011/07/18/un-famine-east-africa.html| archivedate= 20 July 2011 <!--DASHBot-->| deadurl= no}}</ref>
* [[July 21]] &ndash; [[Space Shuttle Atlantis]] lands successfully at [[Kennedy Space Center]] after completing [[STS-135]], concluding NASA's [[space shuttle]] program.<ref name="landing times">{{cite web|title=Atlantis Completes Final Space Shuttle Program Landing at 5:57 a.m. EDT|url=http://www.nasa.gov/mission_pages/shuttle/main/index.html|publisher=NASA|accessdate=21 July 2011|author=Staff| archiveurl= http://web.archive.org/web/20110726190430/http://www.nasa.gov/mission_pages/shuttle/main/index.html| archivedate= 26 July 2011 <!--DASHBot-->| deadurl= no|date=21 July 2011}}</ref>
* [[July 22]] &ndash; [[Anders Behring Breivik]] kills 77 people in [[2011 Norway attacks|twin terrorist attacks]] in Norway, after a bombing in the [[Regjeringskvartalet]] government center in Oslo and a shooting at a political youth camp on the island of [[Utøya]].<ref>{{Cite news | newspaper = The Wall Street Journal | date=23 July 2011 | accessdate=23 July 2011 | first1 = Charles | last1 = Duxbury | first2 = Kjetil | last2 = Hovland | url = http://online.wsj.com/article/SB10001424053111903461104576461862078291234.html?mod=WSJ_hp_LEFTTopStories | title = Savage Terror Attacks | quote = ...at Least 87 Dead | postscript =.}}.</ref><ref>{{Cite news | date=22 July 2011 | accessdate=23 July 2011 | first1 = Michael | last1 = Birnbaum | newspaper = The New York Times | url = http://www.nytimes.com/2011/07/23/world/europe/23oslo.html | title = At Least 80 Are Dead in Norway Shooting | first2 = Elisa | last2 = Mala | first3 = J David | last3 = Goodman | postscript=.| archiveurl= http://web.archive.org/web/20110722213708/http://www.nytimes.com/2011/07/23/world/europe/23oslo.html| archivedate= 22 July 2011 <!--DASHBot-->| deadurl= no}}.</ref><ref>{{Cite news | date=22 July 2011 | accessdate=23 July 2011 | newspaper = The Washington Post | title = Norway attacks: At least 87 dead in shootings at youth conference, Oslo explosion | url = http://www.washingtonpost.com/world/europe/norways-capital-shaken-by-bomb-blast/2011/07/22/gIQABA6dTI_story.html | quote = ...at least 80 people shot to death at a youth political conference outside Oslo after a massive explosion in the capital’s government district killed at least seven people, according to Norwegian police | postscript=. | first=William | last=Wan}}.</ref><ref>{{cite news|url=http://www.rte.ie/news/2011/0730/oslo.html |title=Press say Breivik had planned other attacks|date=30 July 2011|work=[[RTE]]|publisher=[[RTE]]|accessdate=30 July 2011}}</ref>
* [[July 31]]
** In [[Thailand]] over 12.8 million people are affected by [[2011 Thailand floods|severe flooding]]. The [[World Bank]] estimates damages at 1,440 billion [[Thailand baht|baht]] ([[United States dollar|US$]]45 billion).<ref name="time">{{cite news |url=http://www.time.com/time/world/article/0,8599,2101273,00.html |title=Thailand cleans up; Areas remain flooded |agency=Associated Press |publisher=Time |date=December 2, 2011}}</ref> Some areas are still six feet under water, and many factory areas remained closed at the end of the year. 815<ref>{{cite web|url=http://www.thejakartapost.com/news/2011/12/30/death-toll-thai-floods-rises-790.html |title=Death toll of Thai floods rises to 790 |publisher=Thejakartapost.com |date=2011-12-30 |accessdate=2012-05-06}}</ref> people are killed, with 58 of the country's 77 provinces affected.<ref>{{cite web|author=South East Asia correspondent , wires |url=http://www.abc.net.au/news/2011-10-05/27worst27-thai-floods-kill-2242c-threaten-bangkok/3221304/?site=sydney |title=ABC News Australia |publisher=Abc.net.au |date= |accessdate=2012-05-06}}</ref>
** Arab Spring: Because of the uncertaintities associated with a clamp-down of the free press, there are believed to be at least 121 people killed in a [[Syrian Army]] [[Siege of Hama (2011)|tank raid]] on the town of [[Hama]] and over 150 people are reportedly killed across the country.<ref>{{cite web|url=http://english.aljazeera.net/news/middleeast/2011/07/201173143432348733.html |title=english.aljazeera.net |publisher=english.aljazeera.net |date= |accessdate=2012-05-06}}</ref><ref>{{cite web|url=http://english.aljazeera.net/news/middleeast/2011/07/2011731183142996341.html |title=english.aljazeera.net |publisher=english.aljazeera.net |date= |accessdate=2012-05-06}}</ref><ref>{{cite web|author=<!--[if IE 6]> <![endif]--> |url=http://english.alarabiya.net/articles/2011/07/31/160188.html |title=english.aljazeera.net |publisher=English.alarabiya.net |date=2011-07-31 |accessdate=2012-05-06}}</ref> The [[Syrian civil war|total dead]] throughout [[Syria]] may never be known, but an estimate as of September 24 is 3,000.

===August===
* [[August]] &ndash; [[Stock exchange]]s worldwide [[August 2011 stock markets fall|suffer heavy losses]] due to the fears of contagion of the [[European sovereign debt crisis]] and the credit rating downgraded as a result of the [[United States debt-ceiling crisis of 2011|debt-ceiling crisis of the United States]].<ref>{{cite news| url=http://www.bloomberg.com/news/2011-08-06/u-s-credit-rating-cut-by-s-p-for-first-time-on-deficit-reduction-accord.html | work=Bloomberg | first=John | last=Detrixhe | title=U.S. Loses AAA Credit Rating as S&P Slams Debt Levels, Political Process | date=August 6, 2011}}</ref><ref>{{cite news|title=Analysis: France, Britain AAA-ratings under scrutiny|date=8 August 2011|first1=Catherine|last1=Bremer|first2=Olesya|last2=Dmitracova|work=Reuters|location=Paris/London|url=http://www.reuters.com/article/2011/08/08/us-crisis-ratings-idUSTRE7773KG20110808|accessdate=10 August 2011}}</ref>
* [[August 5]]
** NASA announces that its [[Mars Reconnaissance Orbiter]] has captured [[Seasonal flows on warm Martian slopes|photographic evidence]] of possible liquid [[water on Mars]] during warm seasons.
** [[Juno (spacecraft)|Juno]], the first [[Solar Power|solar-powered]] spacecraft on a mission to [[Jupiter]], is launched from [[Cape Canaveral Air Force Station]].<ref>{{cite news|url=http://www.rte.ie/news/2011/0805/nasa.html |title=NASA launches mission to Jupiter|date=5 August 2011|work=[[RTE]]|publisher=[[RTE]]|accessdate=5 August 2011}}</ref>
* [[August 20]]–[[August 28|28]] &ndash; Arab Spring and the Libyan civil war: In the [[Battle of Tripoli (2011)|Battle of Tripoli]], Libyan rebels take control of the nation's capital, effectively overthrowing the government of [[Muammar Gaddafi]].<ref>{{cite web|url=http://blogs.aljazeera.net/liveblog/libya-aug-31-2011-1131 |title=Wednesday, August 31, 2011 - 09:31 GMT+3 - Libya |publisher=Blogs.aljazeera.net |date=2011-08-31 |accessdate=2012-05-06}}</ref><ref>{{cite news|title=Gadhafi Family Members in Algeria, Ambassador Says|url=http://www.cnn.com/2011/WORLD/africa/08/29/libya.algeria.gadhafi/index.html?hpt=hp_c1|date = 29 August 2011 | accessdate=29 August 2011|author= Staff|publisher = CNN}}</ref><ref>{{cite news | author = Staff | date = 23 August 2011 | url = http://www.bbc.co.uk/news/world-africa-14630702 | title = Libya Unrest: Rebels Overrun Gadhafi Tripoli Compound | publisher = BBC News | accessdate = 24 August 2011}}</ref>

===September===
* [[September 5]] &ndash; [[India]] and [[Bangladesh]] sign a pact to end their 40-year [[Bangladesh–India border|border demarcation dispute]].<ref>{{cite web|url=http://ibnlive.in.com/news/indiabangladesh-sign-pact-on-border-demarcation/181937-3.html |title=India-Bangladesh sign pact on border demarcation |publisher=Ibnlive.in.com |date= |accessdate=2012-05-06}}</ref>
* [[September 10]] &ndash; [[Zanzibar ferry sinking]]: The ''[[MV&nbsp;Spice Islander&nbsp;I]]'', carrying at least 800 people, sinks off the coast of [[Zanzibar]], killing 240 people.<ref name="xinhua">[http://news.xinhuanet.com/english2010/world/2011-09/11/c_131133070.htm 197 bodies retrieved in Tanzania ferry accident: Minister] Xinhua 11th September 2011</ref>
* [[September 12]] &ndash; Approximately 100 people die after [[2011 Nairobi pipeline fire|a petrol pipeline explodes]] in [[Nairobi]].<ref>{{cite web|author=Hassan Lali |url=http://www.bbc.co.uk/news/world-africa-14879401 |title=Kenya fire: Nairobi pipeline blaze 'kills at least 75' '&#39;BBC'&#39; |publisher=Bbc.co.uk |date=2011-09-12 |accessdate=2012-05-06}}</ref>
* [[September 17]] &ndash;  [[Occupy Wall Street]] protests begin in the United States. This develops into the [[Occupy movement]] which spreads to 82 countries by October.<ref name="cnn">{{Cite news|work=CNN tech|last=Saba|first=Michael|title=Twitter #occupywallstreet movement aims to mimic Iran|url=http://www.cnn.com/2011/09/16/tech/social-media/twitter-occupy-wall-street/index.html|date=September 17, 2011|accessdate=September 17, 2011}}</ref><ref name="adbusters1">{{cite web|url=http://www.adbusters.org/campaigns/occupywallstreet |title=Occupy Wall Street &#124; September 17th |publisher=Adbusters.org|accessdate=October 6, 2011}}</ref><ref>{{cite news|url=http://www.guardian.co.uk/world/2011/oct/25/egyptian-protesters-occupy-wall-street?newsfeed=true|title=Tahrir Square protesters send message of solidarity to Occupy Wall Street|accessdate=15 November 2011|publisher=The Guardian|date=25 October 2011|location=London|first1=Jack|last1=Shenker|first2=Adam|last2=Gabbatt}}</ref><ref>{{cite web|url =http://aljazeera.net/NR/exeres/F39F8293-C172-4018-9725-1E1184EED075.htm?GoogleStatID=9|title = احتجاجات بـ82 دولة للمطالبة بالعدالة| publisher = AlJazeera.net|accessdate = January 3, 2012}}</ref><ref name="guardian">{{cite news |title=Occupy America: protests against Wall Street and inequality hit 70 cities |author=Joanna Walters|url=http://www.guardian.co.uk/world/2011/oct/08/occupy-america-protests-financial-crisis|newspaper=The Guardian |date=8 October 2011|accessdate=October 14, 2011 |location=London}}</ref><ref name="theatlantic">{{cite news|title=Occupy the World: The '99 Percent' Movement Goes Global |author=Derek Thompson|url=http://www.theatlantic.com/business/archive/2011/10/occupy-the-world-the-99-percent-movement-goes-global/246757/ |newspaper=The Atlantic|date=Oct 15, 2011 |accessdate=October 15, 2011}}</ref><ref>{{cite news |title=Occupy Wall Street protests go global |author=Karla Adam|url=http://www.washingtonpost.com/world/europe/occupy-wall-street-protests-go-global/2011/10/15/gIQAp7kimL_story.html |newspaper=The Washington Post |date=October 15, 2011 |accessdate=November 8, 2011}}</ref><ref>{{cite news |title=Occupy Wall Street protests continue worldwide |author=Karla Adam |url= |newspaper=The Washington Post |date=October 16, 2011 |accessdate=November 8, 2011}}</ref><ref name="guardian2">{{cite news|author=Joanna Walters in Seattle|url=http://www.guardian.co.uk/world/2011/oct/08/occupy-america-protests-financial-crisis |title=Occupy America: protests against Wall Street and inequality hit 70 cities &#124; World news &#124; The Observer |work=The Guardian |location=UK |accessdate=October 13, 2011 |date=8 October 2011}}</ref>
* [[September 19]] &ndash; With 434 dead, the United Nations launches a $357 million appeal for victims of the [[2011 Sindh floods]] in [[Pakistan]].<ref>{{cite web|url=http://www.rferl.org/content/un_appeals_for_millions_to_help_pakistan_flood_victims/24332575.html |title=UN Appeals For $357 Million To Help Pakistan Flood Victims '&#39;Radio Free Europe'&#39; |publisher=Rferl.org |date=2011-09-19 |accessdate=2012-05-06}}</ref>

===October===
* [[October 4]]
** [[2011 Mogadishu bombing]]: 100<ref>{{cite web|author=&nbsp; |url=http://www.voanews.com/policy/editorials/africa/Murder-In-Mogadishu-131808193.html |title=Murder In Mogadishu |publisher=Voanews.com |date=2011-10-13 |accessdate=2012-05-06}}</ref> people are killed in a [[car bombing]] in the [[Somalia|Somali]] capital [[Mogadishu]].<ref>{{cite web|url=http://www.hindustantimes.com/65-dead-in-Somali-car-bombing/Article1-753497.aspx |title=Indo-Asian News Service via '&#39;Hindustan Times'&#39; |publisher=Hindustantimes.com |date=2011-10-04 |accessdate=2012-05-06}}</ref>
** The death toll from the flooding of [[Cambodia]]'s [[Mekong River]] and attendant flash floods reaches 207.<ref>{{cite web|url=http://www.wfp.org/content/floods-claim-207-lives-cambodia |title=Floods claim 207 lives in Cambodia |publisher=Wfp.org |date= |accessdate=2012-05-06}}</ref><ref>{{cite web|url=http://www.philstar.com/Article.aspx?articleId=733860&publicationSubCategoryId=200 |title=Xinhua via '&#39;Philippines Star'&#39; |publisher=Philstar.com |date=2011-10-04 |accessdate=2012-05-06}}</ref>
* [[October 18]] &ndash; [[Israel]] and the [[Palestinian people|Palestinian]] militant organization [[Hamas]] begin a major [[Gilad Shalit prisoner exchange|prisoner swap]], in which the captured [[Israeli Army]] soldier [[Gilad Shalit]] is released by Hamas in exchange for 1,027 Palestinian and [[Israeli-Arab]] prisoners held in Israel, including 280 prisoners serving life sentences for planning and perpetrating terror attacks.<ref>{{cite news| url=http://www.cnn.com/2011/10/18/world/meast/israel-prisoner-swap/index.html?hpt=hp_t1 | work=CNN | title=After 5 years in captivity, Shalit is back home - CNN.com | date=October 19, 2011}}</ref><ref>{{cite news| url=http://www.guardian.co.uk/world/2011/oct/18/gilad-shalit-release-palestinian-exchange | location=London | work=The Guardian | title=Gilad Shalit release: Palestinian prisoner exchange getting under way | date=October 18, 2011}}</ref><ref>{{cite web|url=http://www.jpost.com/DiplomacyAndPolitics/Article.aspx?id=242250 |title=Schalit reunites with parents, PM... JPost - Diplomacy & Politics |publisher=Jpost.com |date=2011-10-18 |accessdate=2012-05-06}}</ref>
* [[October 20]]
** Arab Spring and the Libyan civil war: Libyan leader [[Muammar Gaddafi]] is [[Death of Muammar Gaddafi|killed]] in [[Sirte]], with [[National Liberation Army (Libya)|National Transitional Council forces]] [[Battle of Sirte (2011)|taking control of the city]], and ending the war.<ref>{{cite web|url=http://english.aljazeera.net/news/africa/2011/10/20111020111520869621.html |title=NTC claims capture of Gaddafi - Africa |work=Al Jazeera English |date=2011-10-04 |accessdate=2011-10-20}}</ref><ref>{{cite news|url=http://www.bbc.co.uk/news/world-africa-15387872 |title=BBC News - Col Gaddafi killed |work=BBC|date= October 22, 2011|accessdate=2011-10-20}}</ref><ref>{{cite news|url=http://uk.reuters.com/article/2011/10/20/uk-libya-gaddafi-death-idUKTRE79J2S320111020 |title=Gaddafi dies of wounds - NTC official|work=Reuters UK|agency=Reuters|date= October 20, 2011|accessdate=2011-10-20 |first=Samia |last=Nakhoul}}</ref><ref>{{cite web|url=http://english.aljazeera.net/news/africa/2011/10/20111020111520869621.html |title=Muammar Gaddafi 'killed' in gun battle - Africa |work=Al Jazeera English |date=2011-10-04 |accessdate=2011-10-20}}</ref>
** [[Basque people|Basque]] [[Basque separatism|separatist]] militant organisation [[Euskadi ta Askatasuna|ETA]] declares an end to its 43-year campaign of political violence, which has killed over 800 people since 1968.<ref>{{cite web|url=http://politica.elpais.com/politica/2011/10/19/actualidad/1319056094_153776.html |title=ETA pone fin a 43 años de terror &#124; Política &#124; EL PAÍS |publisher=Politica.elpais.com |date= |accessdate=2012-05-06}}</ref>
* [[October 23]] &ndash; A magnitude 7.2 M<sub>w</sub> [[2011 Van earthquake|earthquake]] jolts eastern Turkey near the [[city of Van]], killing 604 people, and damaging about 2,200 buildings.<ref>{{cite web|author=October 23, 2011 |url=http://earthquake-report.com/2011/10/23/very-strong-dangerous-earthquake-in-eastern-turkey/ |title=2011 Van earthquake |publisher=Earthquake Report |date=2011-10-23 |accessdate=2012-05-06}}</ref>
* [[October 27]] &ndash; After an emergency meeting in Brussels, the European Union announces an agreement to tackle the [[European sovereign debt crisis]] which includes a [[Write-off|writedown]] of 50% of Greek bonds, a recapitalisation of European banks and an increase of the bailout fund of the [[European Financial Stability Facility]] totaling to €1 trillion.<ref name=BBCleaders>{{cite news|title=Leaders agree eurozone debt deal after late-night talks|url=http://www.bbc.co.uk/news/world-europe-15472547|accessdate=27 October 2011|newspaper=BBC News|date=27 October 2011}}</ref><ref>{{cite news|last=Bhatti|first=Jabeen|title=EU leaders reach a deal to tackle debt crisis|url=http://www.usatoday.com/money/world/story/2011-10-25/euro-summit/50919216/1?csp=34news|accessdate=27 October 2011|newspaper=USA Today|date=27 October 2011}}</ref>
* [[October 31]]
** Date selected by the UN as the symbolic date when global population [[Day of Seven Billion|reaches seven billion]].<ref>{{cite news|title=Population seven billion: UN sets out challenges|url=http://www.bbc.co.uk/news/world-15459643|publisher=BBC News|date=2011-10-26|accessdate=2011-10-30}}</ref>
** [[UNESCO]] admitted [[Palestinian National Authority|Palestine]] as a member, following a vote in which 107 member states supported and 14 opposed.<ref>{{cite web|url=http://www.unesco.org/new/en/media-services/single-view/news/general_conference_admits_palestine_as_unesco_member_state/|title=General Conference admits Palestine as UNESCO Member|date=2011-10-31|accessdate=2011-12-11}}</ref>

=== November ===
* [[November 26]] &ndash; The [[Mars Science Laboratory]] rover Curiosity, the most elaborate Martian exploration vehicle to date, is launched from the [[Kennedy Space Center]]. It lands on [[Mars]] on [[August 6]], [[2012]].<ref>{{cite news | first=Marcia | last=Dunn | title=NASA launches world’s largest rover to Mars  | url=http://www.theglobeandmail.com/news/technology/science/nasa-launches-worlds-largest-rover-to-mars/article2250839/ | location =Cape Canaveral, Florida | agency=The Associated Press | newspaper=The Globe and Mail | date=26 November 2011}}</ref><ref>{{cite news | first=Irene | last=Klotz | title=NASA rover launched to seek out life clues on Mars | url=http://uk.reuters.com/article/2011/11/26/uk-space-mars-idUKTRE7AP0EV20111126 | location=Cape Canaveral, Florida | date=27 November 2011 | agency=Reuters }}</ref><ref>{{cite news | first= | last= | title=NASA launches new Mars rover  | url=http://www.aljazeera.com/video/americas/2011/11/2011112682011425406.html | location= | date=26 November 2011 | agency=Al Jazeera }}</ref>

=== December ===
* [[December 15]] &ndash; The [[United States]] formally declares an [[Withdrawal of U.S. troops from Iraq|end]] to the [[Iraq War]]. While this ends the [[Iraqi insurgency|insurgency]], it begins [[Iraqi insurgency (post-U.S. withdrawal)|another]].<ref>{{cite news|title=US flag ceremony ends Iraq operation|url=http://www.bbc.co.uk/news/world-us-canada-16192105|publisher=BBC|accessdate=15 December 2011|date=December 15, 2011}}</ref><ref>{{cite news |url=http://thehill.com/blogs/defcon-hill/operations/199581-panetta-marks-end-of-iraq-war-|title= Panetta marks Iraq war's end in Baghdad|date=December 15, 2011|work= DEFCON Hill – The HILL’S Defense Blog  |first=Jonathan |last=Easley|accessdate=15 December 2011}}</ref><ref>{{cite news |url=http://www.independent.co.uk/news/world/middle-east/us-lowers-flag-to-end-iraq-war-6277340.html|title= US lowers flag to end Iraq war|date=December 15, 2011|agency=Associated Press |accessdate=15 December 2011}}</ref><ref>{{cite news |url=http://montreal.ctv.ca/servlet/an/local/CTVNews/20111215/leon-panetta-us-war-iraq-111215/20111215/?hub=MontrealHome|title= U.S. formally ends Iraq war with little fanfare|date=December 15, 2011|agency= Associated Press |accessdate=15 December 2011}}</ref><ref>{{cite news |url=http://www.politico.com/news/stories/1211/70480.html|title= Leon Panetta marks end of Iraq war|date=December 15, 2011|work= POLITICO.com  |first=Tim |last=Mak|accessdate=15 December 2011}}</ref>
* [[December 16]] &ndash; [[Tropical Storm Washi (2011)|Tropical Storm Washi]] causes 1,268 [[flash flood]] fatalities in the [[Philippines]], with 85 people officially listed as missing.<ref name="washi official">{{cite web|url=http://www.ndrrmc.gov.ph/attachments/article/358/NDRRMC%20Update%20SitRep%20No%2023%20re%20TS%20SENDONG.pdf|title=Effects of Tropical Storm "Sendong" (Washi) and Emergency Operations|date=30 December 2011|publisher=National Disaster Risk Reduction and Management Council|accessdate=1 January 2012|location=Philippines}}</ref>
* [[December 29]] &ndash; [[Samoa]] and [[Tokelau]] move from east to west of the [[International Date Line]], thereby skipping December 30, in order to align their time zones better with their main trading partners.<ref name="washi official">{{cite news|url=http://www.chicagotribune.com/news/nationworld/sns-ap-as-samoa-dateline,0,2803590.story|title=Back to the future: Samoa and Tokelau to cross international date line, jump forward a day|date=21 December 2011|publisher=Chicago Tribune|accessdate=29 December 2011}}</ref>

==Deaths==
{{Main|Deaths in 2011}}
{{Further|:Category:2011 deaths}}
<!--Before adding anybody with fewer than nine non-English language Wikipedia articles, please obtain consensus to do so on this article's talk page. Without this consensus, any editor may remove any subject who has fewer than nine non-English language Wikipedia articles. Editors may also seek consensus to remove subjects that appear to be of limited international or historical notability, even if those subjects have nine or more non-English articles. Thanks. -->

===January===
[[File:Gerry Rafferty.jpg|thumb|120px|[[Gerry Rafferty]]]]
* [[January 2]]
** [[Anne Francis]], American actress (b. [[1930]])
** [[Pete Postlethwaite]], British actor (b. [[1946]])
** [[Richard Winters]], American paratrooper (b. [[1918]])
* [[January 4]]
** [[Ali-Reza Pahlavi|Prince Ali-Reza Pahlavi]] of Iran (b. [[1966]])
** [[Gerry Rafferty]], Scottish musician (b. [[1947]])
* [[January 15]]
** [[Nat Lofthouse]], English footballer (b. [[1925]])
** [[Susannah York]], British actress (b. [[1939]])
* [[January 18]] &ndash; [[Sargent Shriver]], American politician and diplomat (b. [[1915]])
* [[January 21]] &ndash; [[Dennis Oppenheim]], American artist (b. [[1938]])
* [[January 24]] &ndash; [[Bernd Eichinger]], German film producer and director (b. [[1949]])
* [[January 29]] &ndash; [[Milton Babbitt]], American composer (b. [[1916]])
* [[January 30]] &ndash; [[John Barry (composer)|John Barry]], English composer (b. [[1933]])

===February===
[[File:Jane Russell in Gentlemen Prefer Blondes trailer 3.jpg|thumb|120px|[[Jane Russell]]]]
* [[February 3]] &ndash; [[Maria Schneider (actress)|Maria Schneider]], French actress (b. [[1952]])
* [[February 5]] &ndash; [[Brian Jacques]], British author (b. [[1939]])
* [[February 6]]
** [[Josefa Iloilo]], 3rd President of Fiji (b. [[1920]])
** [[Gary Moore]], British musician (b. [[1952]])
* [[February 8]] &ndash; [[Cesare Rubini]], Italian basketball player and coach (b. [[1923]])
* [[February 14]] &ndash; [[George Shearing]], British-American jazz pianist (b. [[1919]])
* [[February 27]] &ndash; [[Necmettin Erbakan]], 25th Prime Minister of Turkey (b. [[1926]])
* [[February 28]] &ndash; [[Jane Russell]], American actress (b. [[1921]])

===March===
[[File:Alberto-granado-scaled.JPG|thumb|120px|[[Alberto Granado]]]]
[[File:Taylor, Elizabeth posed.jpg|thumb|120px|[[Elizabeth Taylor]]]]
* [[March 4]]
** [[Krishna Prasad Bhattarai]], 30th Prime Minister of Nepal (b. [[1924]])
** [[Simon van der Meer]], Dutch Nobel physicist (b. [[1925]])
* [[March 5]] &ndash; [[Alberto Granado]], Cuban writer and scientist (b. [[1922]])
* [[March 6]] &ndash; [[Ján Popluhár]], Slovak footballer (b. [[1935]])
* [[March 15]] &ndash; [[Nate Dogg]], American rapper (b. [[1969]])
* [[March 17]] &ndash; [[Michael Gough]], British actor (b. [[1916]])
* [[March 18]] &ndash; [[Warren Christopher]], American diplomat (b. [[1925]])
* [[March 21]] &ndash; [[Nikolai Andrianov]], Soviet-Russian gymnast (b. [[1952]])
* [[March 23]] &ndash; [[Elizabeth Taylor]], British-American actress (b. [[1932]])
* [[March 26]]
** [[Paul Baran]], Polish-American computer engineer (b. [[1926]])
** [[Geraldine Ferraro]], American politician (b. [[1935]])
** [[Diana Wynne Jones]], British writer (b. [[1934]])
* [[March 27]] &ndash; [[Farley Granger]], American actor (b. [[1925]])
* [[March 29]] &ndash; [[José Alencar]], Brazilian politician (b. [[1931]])

===April===
[[File:William n lipscomb jr.jpg|thumb|120px|[[William Lipscomb]]]]
* [[April 5]]
** [[Baruch Samuel Blumberg]], American physician (b. [[1925]])
** [[Ange-Félix Patassé]], 5th President of the Central African Republic (b. [[1937]])
* [[April 9]] &ndash; [[Sidney Lumet]], American film director (b. [[1924]])
* [[April 14]] &ndash; [[William Lipscomb]], American chemist (b. [[1919]])
* [[April 19]] &ndash; [[Grete Waitz]], Norwegian athlete (b. [[1953]])
<!-- Please do not add Elisabeth Sladen here as she does not meet the requirements for inclusion. See the talk page-->
* [[April 24]] &ndash; [[Sathya Sai Baba]],  Indian spiritual leader (b. [[1926]])
* [[April 30]] &ndash; [[Ernesto Sabato]], Argentine writer (b. [[1911]])

===May===
[[File:Osama bin Laden portrait cropped.jpg|thumb|120px|[[Osama bin Laden]]]]
[[File:Rosalyn Yalow.jpg|thumb|120px|[[Rosalyn Yalow]]]]
* [[May 2]] &ndash; [[Osama bin Laden]], Saudi-born leader of Al-Qaeda (b. [[1957]])
* [[May 3]] &ndash; [[Jackie Cooper]], American actor (b. [[1922]])
* [[May 7]]
** [[Seve Ballesteros]], Spanish golfer (b. [[1957]])
** [[Willard Boyle]], Canadian Nobel physicist (b. [[1924]])
* [[May 9]] &ndash; [[Lidia Gueiler Tejada]], 67th President of Bolivia (b. [[1921]])
* [[May 16]] &ndash; [[Samuel Wanjiru]], Kenyan athlete (b. [[1986]])
* [[May 19]] &ndash; [[Garret FitzGerald]], 7th Taoiseach of Ireland (b. [[1926]])
* [[May 20]] &ndash; [[Randy Savage]], American professional wrestler (b. [[1952]])
* [[May 27]]
** [[Jeff Conaway]], American actor (b. [[1950]])
** [[Gil Scott-Heron]], American poet and musician (b. [[1949]])
* [[May 29]]
** [[Sergei Bagapsh]], Georgian-born politician (b. [[1949]])
** [[Ferenc Mádl]], 2nd President of Hungary (b. [[1931]])
* [[May 30]] &ndash; [[Rosalyn Sussman Yalow]], American physicist (b. [[1921]])
* [[May 31]] &ndash; [[Pauline Betz]], American tennis player (b. [[1919]])

===June===
[[File:KevorkianUCLARoyce.jpg|thumb|120px|[[Jack Kevorkian]]]] 
* [[June 3]] &ndash; [[Jack Kevorkian]], American euthanasia advocate (b. [[1928]])
* [[June 4]] &ndash; [[Lawrence Eagleburger]], American diplomat (b. [[1930]])
* [[June 7]] &ndash; [[Jorge Semprún]], Spanish writer and politician (b. [[1923]])
* [[June 9]] &ndash; [[M.F. Hussain]], Indian painter (b. [[1915]])
* [[June 10]] &ndash; [[Patrick Leigh Fermor]], British travel writer, scholar and soldier (b. [[1915]])
* [[June 18]]
** [[Frederick Chiluba]], 2nd President of Zambia (b. [[1943]])
** [[Clarence Clemons]], American musician and actor (b. [[1942]])
<!--DO NOT ADD RYAN DUNN, see talk-->
* [[June 23]] &ndash; [[Peter Falk]], American actor (b. [[1927]])

===July===
[[File:ItamarFranco.jpg|thumb|120px||[[Itamar Franco]]]]
* [[July 2]] &ndash; [[Itamar Franco]], 37th President of Brazil (b. [[1930]])
* [[July 4]] &ndash; [[Otto von Habsburg|Archduke Otto of Austria]], (b. [[1912]])
* [[July 5]] &ndash; [[Cy Twombly]], American painter (b. [[1928]])
* [[July 8]] &ndash; [[Betty Ford]], American feminist, activist, philanthropist and former First Lady (b. [[1918]])
* [[July 10]] &ndash; [[Roland Petit]], French choreographer and dancer (b. [[1924]])
* [[July 12]] &ndash; [[Tom Gehrels]], American astronomer (b. [[1925]])
* [[July 17]] &ndash; [[Juan Maria Bordaberry]], 36th President of Uruguay (b. [[1928]])
* [[July 20]] &ndash; [[Lucian Freud]], German-born British painter (b. [[1922]])
* [[July 23]]
** [[Robert Ettinger]], American academic (b. [[1918]])
** [[Nguyen Cao Ky]], 8th Prime Minister of the Republic of Vietnam (b. [[1930]])
** [[Amy Winehouse]], British singer (b. [[1983]])
* [[July 25]] &ndash; [[Mihalis Kakogiannis]], Cypriot filmmaker (b. [[1922]])
* [[July 28]] &ndash; [[Abdul Fatah Younis]], Libyan army commander (b. [[1944]])
* [[July 30]] &ndash; [[Mario Echandi Jiménez]], 47th President of Costa Rica (b. [[1915]])

===August===
[[File:holkeri.jpg|thumb|120px|[[Harri Holkeri]]]]
* [[August 2]] &ndash; [[Baruj Benacerraf]], Venezuelan-born American Nobel immunologist (b. [[1920]])
* [[August 3]] &ndash; [[Bubba Smith]], American football player and actor (b. [[1945]])
* [[August 7]]
** [[Harri Holkeri]], 57th Prime Minister of Finland (b. [[1937]])
** [[Nancy Wake]], New Zealand-born French Resistance fighter (b. [[1912]])
* [[August 14]] &ndash; [[Shammi Kapoor]], Indian film actor and director (b. [[1931]])
* [[August 16]] &ndash; [[Andrej Bajuk]], 3rd Prime Minister of the Republic of Slovenia (b. [[1943]])
* [[August 19]] &ndash; [[Raúl Ruiz (director)|Raúl Ruiz]], Chilean film director (b. [[1941]])
* [[August 22]] &ndash; [[Jack Layton]], Canadian politician (b. [[1950]])
* [[August 31]] &ndash; [[Valery Rozhdestvensky]], Soviet-Russian cosmonaut (b. [[1939]])

===September===
[[File:Wangari Maathai no Brasil.jpg|thumb|120px|[[Wangari Maathai]]]]
* [[September 7]] &ndash; Victims of the [[2011 Lokomotiv Yaroslavl air disaster]]
** [[Vitaly Anikeyenko]], Ukrainian-Russian hockey player (b. [[1987]])
** [[Mikhail Balandin]], Russian hockey player (b. [[1980]])
** [[Gennady Churilov]], Russian hockey player (b. [[1987]])
** [[Pavol Demitra]], Slovakian hockey player (b. [[1974]])
** [[Robert Dietrich]], Kazakhstani-German hockey player (b. [[1986]])
** [[Marat Kalimulin]], Russian hockey player (b. [[1988]])
** [[Alexander Kalyanin]], Russian hockey player (b. [[1987]])
** [[Alexander Karpovtsev]], Russian hockey player (b. [[1970]])
** [[Andrei Kiryukhin]], Russian hockey player (b. [[1987]])
** [[Nikita Klyukin]], Russian hockey player (b. [[1989]])
** [[Igor Korolev]], Russian hockey player (b. [[1970]])
** [[Stefan Liv]], Polish-born Swedish hockey player (b. [[1980]])
** [[Jan Marek (ice hockey b. 1979)|Jan Marek]], Czech hockey player (b. [[1979]])
** [[Brad McCrimmon]], Canadian hockey player (b. [[1959]])
** [[Sergei Ostapchuk]], Belarusian hockey player (b. [[1990]])
** [[Karel Rachůnek]], Czech hockey player (b. [[1979]])
** [[Ruslan Salei]], Belarusian hockey player (b. [[1974]])
** [[Maxim Shuvalov]], Russian hockey player (b. [[1993]])
** [[Kārlis Skrastiņš]], Latvian hockey player (b. [[1974]])
** [[Pavel Snurnitsyn]], Russian hockey player (b. [[1992]])
** [[Daniil Sobchenko]], Ukrainian-Russian hockey player (b. [[1991]])
** [[Ivan Tkachenko (ice hockey)|Ivan Tkachenko]], Russian hockey player (b. [[1979]])
** [[Pavel Trakhanov]], Russian hockey player (b. [[1978]])
** [[Yuri Urychev]], Russian hockey player (b. [[1991]])
** [[Josef Vašíček]], Czech hockey player (b. [[1980]])
** [[Alexander Vasyunov]], Russian hockey player (b. [[1988]])
** [[Alexander Vyukhin]], Ukrainian-Russian hockey player (b. [[1973]])
** [[Artem Yarchuk]], Russian hockey player (b. [[1990]])
* [[September 8]] &ndash; [[Vo Chi Cong]], 5th President of Vietnam (b. [[1912]])
* [[September 10]] &ndash; [[Cliff Robertson]], American actor (b. [[1923]])
* [[September 11]] &ndash; [[Andy Whitfield]], Welsh actor and model (b. [[1972]])
* [[September 12]] &ndash; [[Alexander Galimov]], Russian hockey player (b. [[1985]])
* [[September 13]] &ndash; [[Richard Hamilton (artist)|Richard Hamilton]], British painter and collage artist (b. [[1922]])
* [[September 14]] &ndash; [[Rudolf Mössbauer]], German Nobel physicist (b. [[1929]])
* [[September 19]] &ndash; [[George Cadle Price]], 1st Prime Minister of Belize (b. [[1919]])
* [[September 20]] &ndash; [[Burhanuddin Rabbani]], President of Afghanistan from 1992 to 1996 (b. [[1940]])
* [[September 22]] &ndash; [[Aristides Pereira]], 1st President of Cape Verde (b. [[1923]])
* [[September 25]] &ndash; [[Wangari Maathai]], Kenyan veterinary anatomist and Nobel Peace Prize laureate (b. [[1940]])
* [[September 27]] &ndash; [[Imre Makovecz]], Hungarian architect (b. [[1935]])
* [[September 30]]
** [[Anwar al-Awlaki]], American-born terrorist and Islamist militant (b. [[1971]])
** [[Ralph M. Steinman]], Canadian Nobel immunologist and cell biologist (b. [[1943]])

===October===
[[File:Steve Jobs Headshot 2010-CROP.jpg|thumb|130px|[[Steve Jobs]]]]
[[File:Muammar al-Gaddafi 1-1.jpg|thumb|120px|[[Muammar Gaddafi]]]]
* [[October 1]] &ndash; [[Sven Tumba]], Swedish hockey player (b. [[1931]])
* [[October 5]]
** [[Steve Jobs]], American computer entrepreneur (b. [[1955]])
** [[Charles Napier (actor)|Charles Napier]], American actor (b. [[1936]])
* [[October 6]] &ndash; [[Diane Cilento]], Australian actress (b. [[1933]])
* [[October 7]] &ndash; [[Ramiz Alia]], 1st President of Albania (b. [[1925]])
* [[October 12]] &ndash; [[Dennis Ritchie]], American computer scientist (b. [[1941]])
* [[October 16]] &ndash; [[Dan Wheldon]], English racing car driver (b. [[1978]])
* [[October 20]] &ndash; [[Muammar Gaddafi]], Libyan leader (b. [[1942]])
* [[October 22]] &ndash; [[Sultan, Crown Prince of Saudi Arabia]], (b. [[1930]])
* [[October 23]]
** [[Herbert A. Hauptman]], American mathematician and Nobel laureate in chemistry (b. [[1917]])
** [[Marco Simoncelli]], Italian motorcycle road racer (b. [[1987]])
* [[October 24]] &ndash; [[John McCarthy (computer scientist)|John McCarthy]], American computer scientist (b. [[1927]])
* [[October 31]] &ndash; [[Flórián Albert, Sr.|Flórián Albert]], Hungarian footballer (b. [[1941]])

===November===
[[File:Joe Frazier awarded by the Daily News.jpg|thumb|120px|[[Joe Frazier]]]]
* [[November 4]] &ndash; [[Alfonso Cano]], Colombian militant leader (b. [[1948]])
* [[November 5]] &ndash; [[Norman Foster Ramsey, Jr.]], American Nobel physicist (b. [[1915]])
* [[November 7]] &ndash; [[Joe Frazier]], American boxer (b. [[1944]])
* [[November 8]] &ndash; [[Valentin Kozmich Ivanov|Valentin Ivanov]], Russian footballer (b. [[1934]])
* [[November 9]] &ndash; [[Har Gobind Khorana]], Indian-born American Nobel biochemist (b. [[1922]])
* [[November 21]] &ndash; [[Anne McCaffrey]], American writer (b. [[1926]])
* [[November 22]] &ndash; [[Paul Motian]], American jazz drummer (b. [[1931]])
* [[November 25]] &ndash; [[Vasily Alekseyev]], Soviet-Russian weightlifter (b. [[1942]])
* [[November 27]]
** [[Ken Russell]], British film director (b. [[1927]])
** [[Gary Speed]], Welsh footballer and coach (b. [[1969]])
* [[November 28]]
** [[Ante Marković]], 9th Prime Minister of SFR Yugoslavia (b. [[1924]])
** [[Charles Thomas Kowal]], American astronomer (b. [[1940]])

===December===
[[Image:Harry Morgan 1975.jpg|120px|thumb|[[Harry Morgan]]]]
[[Image:Kim Jong-il on August 24, 2011.jpg|120px|thumb|[[Kim Jong-il]]]]
* [[December 1]] &ndash; [[Christa Wolf]], German writer (b. [[1929]])
* [[December 4]] &ndash; [[Sócrates]], Brazilian footballer (b. [[1954]])
* [[December 5]] &ndash; [[Violetta Villas]], Polish singer (b. [[1938]])
* [[December 7]] &ndash; [[Harry Morgan]], American actor (b. [[1915]])
* [[December 8]] &ndash; [[Sir Zelman Cowan]], 19th Governor-General of Australia (b. [[1919]])
* [[December 14]] &ndash; [[Joe Simon]], American comic book writer and artist (b. [[1913]])
* [[December 15]] &ndash; [[Christopher Hitchens]], British-American writer (b. [[1949]])
* [[December 17]]
** [[Cesária Évora]], Cape Verdean singer (b. [[1941]])
** [[Kim Jong-il]], Supreme Leader of the Democratic People’s Republic of Korea (b. [[1941]])
* [[December 18]] &ndash; [[Václav Havel]], Czech playwright, 10th President of Czechoslovakia and 1st President of the Czech Republic (b. [[1936]])
* [[December 24]] &ndash; [[Johannes Heesters]], Dutch actor and singer (b. [[1903]])
* [[December 27]]
** [[Clifford Darling]], 4th Governor-General of the Bahamas (b. [[1922]])
** [[Helen Frankenthaler]], American abstract expressionist painter (b. [[1928]])
{{-}}

==Nobel Prizes==
[[File:Nobel medal.png|right|100px]]
* [[Nobel Prize in Chemistry|Chemistry]] &ndash; [[Dan Shechtman]]<ref>{{cite news |url=http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2011/press.html |title=The Nobel Prize in Chemistry 2011 |date=2011-10-05 |publisher=Nobel Foundation |accessdate=2011-10-05}}</ref>
* [[Nobel Prize in Economics|Economics]] &ndash; [[Christopher A. Sims]] and [[Thomas J. Sargent]]<ref>{{cite news|url=http://www.nobelprize.org/nobel_prizes/economics/laureates/2011/|title= The Nobel Prize in Economics 2011|publisher=Nobel Foundation|accessdate=2011-10-20}}</ref>
* [[Nobel Prize in Literature|Literature]] &ndash; [[Tomas Tranströmer]]<ref>{{cite news|url=http://www.nobelprize.org/nobel_prizes/literature/laureates/2011/ |title=The Nobel Prize in Literature 2011 |date=2011-10-06 |publisher=Nobel Foundation |accessdate=2011-10-06}}</ref>
* [[Nobel Prize for Peace|Peace]] &ndash; [[Ellen Johnson Sirleaf]], [[Leymah Gbowee]] and [[Tawakel Karman]]<ref>{{cite news|url=http://www.nobelprize.org/nobel_prizes/peace/laureates/2011/ |title=The Nobel Peace Prize 2011 |date=2011-10-07 |publisher=Nobel Foundation |accessdate=2011-10-07}}</ref>
* [[Nobel Prize in Physics|Physics]] &ndash; [[Saul Perlmutter]], [[Adam G. Riess]], and [[Brian P. Schmidt]]<ref>{{cite web|url=http://www.nobelprize.org/nobel_prizes/physics/laureates/2011/press.html |title=The 2011 Nobel Prize in Physics - Press Release |publisher=Nobelprize.org |date=2011-10-04 |accessdate=2012-05-06}}</ref>
* [[Nobel Prize in Physiology or Medicine|Physiology or Medicine]] &ndash; [[Bruce A. Beutler]], [[Jules A. Hoffmann]], and [[Ralph M. Steinman]]<ref>{{cite web|url=http://www.nobelprize.org/nobel_prizes/medicine/laureates/2011/ |title=The Nobel Prize in Physiology or Medicine 2011 |publisher=Nobelprize.org |date= |accessdate=2012-05-06}}</ref>

==Major religious holidays==
* [[January 6]] &ndash; [[Christmas]] (celebrated by the [[Armenian Church]])
* [[January 7]] &ndash; [[Christmas]] ([[Eastern Christianity]])
* [[February 1]] &ndash; [[Imbolc]], a [[cross-quarter day]]
* [[March 8]] &ndash; [[Shrove Tuesday]] ([[Mardi Gras]]), end of [[Carnival]] season
* [[March 9]] &ndash; [[Ash Wednesday]] (first day of [[Lent]])
* [[March 20]] &ndash; [[Holi]]
* [[March 21]] &ndash; (Northern hemisphere) Vernal [[equinox]], also known as [[Ostara]] & Persian New Year
* [[April 18]] &ndash; [[Passover]] begins at sundown
* [[April 24]] &ndash; [[Easter]] (''Western'' and ''Orthodox'')
* [[May 1]] &ndash; [[Beltane]], a [[Cross-quarter day]]
* [[May 17]] &ndash; [[Vesak]] (Buddhism)
* [[June 7]] &ndash; [[Shavuot]] begins
* [[August 1]]
** [[Ramadan]] begins (Islam)
** [[Lammas]], a [[Cross-quarter day]]
* [[August 31]] &ndash; [[Eid al-Fitr]]
* [[September 1]] &ndash; [[Ganesh Chaturthi]]
* [[September 11]] &ndash; [[Anant Chaturdashi]]
* [[September 23]] &ndash; (Northern hemisphere) Autumnal [[equinox]], also known as [[Mabon (Wicca)|Mabon]]
* [[September 28]] &ndash; [[Rosh Hashana]] begins at sundown
* [[October 2]] to [[October 6]] &ndash; [[Durga Puja]]
* [[October 7]] &ndash; [[Yom Kippur]] begins at sundown
* [[October 26]] &ndash; [[Diwali]], a religious holiday in [[Hinduism]]
* [[November 6]] &ndash; [[Eid al-Adha]]
* [[November 26]] &ndash; [[Islamic New Year]]
* [[December 20]] &ndash; [[Hanukkah]] begins at sundown
* [[December 25]] &ndash; [[Christmas]] ([[Western Christianity]])

==In fiction==
{{main|Works of fiction set in 2011}}

==References==
{{Portal|2010s}}
{{Reflist|30em}}

{{Events by month links}}

{{DEFAULTSORT:2011}}
[[Category:2011| ]]";}}}}}}